// <auto-generated />
namespace WheelsPrime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbfully_MAPPED : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbfully_MAPPED));
        
        string IMigrationMetadata.Id
        {
            get { return "201512092226409_dbfully_MAPPED"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
